on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: Node 20.11.1
      uses: actions/setup-node@v1
      with:
        node-version: 20.11.1

    - name: Install and build
      run: |
        npm i
        npm run build

    # - name: Check if SENTRY_AUTH_TOKEN is present
    #   run: echo "Token is set"
    #   if: env.SENTRY_AUTH_TOKEN != ''

    # - name: 🛰️ Upload source maps to Sentry
    #   run: |
    #     npx sentry-cli sourcemaps inject --org smartweb-kw --project portfolio-angular ./dist
    #     npx sentry-cli sourcemaps upload -- \
    #       --org smartweb-kw \
    #       --project portfolio-angular \
    #       --include ./dist/portfolio/browser \
    #       --url-prefix '~/' \
    #       --rewrite \
    #       --validate
    #   env:
    #     SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
    #     SENTRY_ORG: smartweb-kw
    #     SENTRY_PROJECT: portfolio-angular

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.1
      with:
        server: albin-schmid.com
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: dist/portfolio/browser/
        server-dir: /albin-schmid.com/
        protocol: ftps